export {default as WhiteHeadphone} from './images/HeadphoneWhite.jpg'
export {default as blacktws} from './images/blacktws.jpg'
export {default as blackkey} from './images/mainblackkey.jpg'
export {default as androidphone} from'./images/androidphone.jpg'
export {default as microwaveold} from './images/micowaveold.jpg'
export {default as penblack} from './images/penblack.jpg'
export {default as hangingheadphone} from './images/hangingheadphone.jpg'
export {default as applekey} from './images/applekey.jpg'
export {default as iphonetable} from './images/iphoneOnTable.jpg'
export {default as airpod} from './images/airpodsclose.jpg'
export {default as  mouse} from './images/mouse1.jpg'
export {default as silvermic} from './images/silvermic.jpg'
export {default as airpod1stgen} from './images/airpods.jpg'
export {default as lgphone} from './images/androidPotrait.jpg'
export {default as blackmicrophone} from './images/blackbackmicrophone.jpg'
export {default as blackheadphone} from './images/blackheadphone.jpg'
export {default as curvyfridge} from './images/curvyfridge.jpg'
export {default as expensivecam} from './images/expensivecam.jpg'
export {default as graphicscard} from './images/Graphics card.jpg'
export {default as iphonewhite} from './images/iphonewhite.jpg'
export {default as iphonewhite2} from './images/iphoneWhite2.jpg'
export {default as laptopbrowntable} from './images/laptopbrowntable.jpg'
export {default as laptopoldlook} from './images/laptopoldlook.jpg'
export {default as laptopwhiteback} from './images/laptopwhiteback.jpg'
export {default as laptopwithplant} from './images/laptopwithplant.jpg'
export {default as modernlappy} from './images/modernlappy.jpg'
export {default as  mouse2} from './images/mouse2.jpg'
export {default as  oldblacktv} from './images/oldblacktv.jpg'
export {default as  PC} from './images/PC.jpg'
export {default as  silverfridge} from './images/silverfridge.jpg'
export {default as  sonycamera} from './images/sonycamera.jpg'
export {default as  toymicrowave} from './images/toymicrowave.jpg'
export {default as  tvbrownroom} from './images/tvbrownroom.jpg'
export {default as  tvdesign} from './images/tvdesign.jpg'
export {default as  tvsideview} from './images/tvsideview.jpg'
export {default as  tvsmalltable} from './images/tvSmallTable.jpg'
export {default as  tvwhiteback} from './images/tvwhiteback.jpg'
export {default as  typecstack} from './images/typecStack.jpg'
export {default as  vintagetv} from './images/vintagetv.jpg'
export {default as  washingmachinehome} from './images/washingmachinehome.jpg'
export {default as  washingmachinegroup} from './images/washingmashinegroup.jpg'
export {default as  whitemicrowave} from './images/whitemicrowave.jpg'
export {default as  whitepen} from './images/whitepen.jpg'
export {default as  wiredpods} from './images/wiredpods.jpg'


