export {default as WhiteHeadphone} from './images/HeadphoneWhite.jpg'
export {default as blacktws} from './images/blacktws.jpg'
export {default as blackkey} from './images/mainblackkey.jpg'
export {default as androidphone} from'./images/androidphone.jpg'
export {default as microwaveold} from './images/micowaveold.jpg'
export {default as penblack} from './images/penblack.jpg'
export {default as hangingheadphone} from './images/hangingheadphone.jpg'
export {default as applekey} from './images/applekey.jpg'
export {default as iphonetable} from './images/iphoneOnTable.jpg'
export {default as airpod} from './images/airpodsclose.jpg'
export {default as  mouse} from './images/mouse1.jpg'
export {default as silvermic} from './images/silvermic.jpg'